### Lab-assignment 3 NLP U24AI038

1. Construct a deterministic finite automaton (DFA) that recognizes valid simplified English
words. An English word, for this problem, is defined as a string that:
>- Starts with an lowercase letter
>- Followed by zero or more lowercase letters

That is, the string must:
>- Not start with a digit or punctuation
>- Not contain uppercase letters after the first character
>- Not contain spaces, digits, or special characters
Output Format:
If a string is accepted, output Accepted else Not Accepted.
>-Accepted: cat, dog, a, zebra
Not Accepted: dog1, 1dog, DogHouse, Dog_house, cats (starts with a space)

In [26]:
import string
states = {"q0", "q1", "q2"}
input_symbols = set(string.printable)

In [27]:
initial_state = "q0"
final_states = {"q1"}

In [28]:
lower_case = set(string.ascii_lowercase)
transitions = {}
q0_transition = {}
for ch in string.printable:
    if ch in lower_case:
        q0_transition[ch] = "q1"
    else:
        q0_transition[ch] = "q2"

q1_transition = {}
for ch in string.printable:
    if ch in lower_case:
        q1_transition[ch] = "q1"
    else:
        q1_transition[ch] = "q2"

q2_transition = {}
for ch in string.printable:
    q2_transition[ch] = "q2"

transitions["q0"] = q0_transition
transitions["q1"] = q1_transition
transitions["q2"] = q2_transition
transitions

{'q0': {'0': 'q2',
  '1': 'q2',
  '2': 'q2',
  '3': 'q2',
  '4': 'q2',
  '5': 'q2',
  '6': 'q2',
  '7': 'q2',
  '8': 'q2',
  '9': 'q2',
  'a': 'q1',
  'b': 'q1',
  'c': 'q1',
  'd': 'q1',
  'e': 'q1',
  'f': 'q1',
  'g': 'q1',
  'h': 'q1',
  'i': 'q1',
  'j': 'q1',
  'k': 'q1',
  'l': 'q1',
  'm': 'q1',
  'n': 'q1',
  'o': 'q1',
  'p': 'q1',
  'q': 'q1',
  'r': 'q1',
  's': 'q1',
  't': 'q1',
  'u': 'q1',
  'v': 'q1',
  'w': 'q1',
  'x': 'q1',
  'y': 'q1',
  'z': 'q1',
  'A': 'q2',
  'B': 'q2',
  'C': 'q2',
  'D': 'q2',
  'E': 'q2',
  'F': 'q2',
  'G': 'q2',
  'H': 'q2',
  'I': 'q2',
  'J': 'q2',
  'K': 'q2',
  'L': 'q2',
  'M': 'q2',
  'N': 'q2',
  'O': 'q2',
  'P': 'q2',
  'Q': 'q2',
  'R': 'q2',
  'S': 'q2',
  'T': 'q2',
  'U': 'q2',
  'V': 'q2',
  'W': 'q2',
  'X': 'q2',
  'Y': 'q2',
  'Z': 'q2',
  '!': 'q2',
  '"': 'q2',
  '#': 'q2',
  '$': 'q2',
  '%': 'q2',
  '&': 'q2',
  "'": 'q2',
  '(': 'q2',
  ')': 'q2',
  '*': 'q2',
  '+': 'q2',
  ',': 'q2',
  '-': 'q2',
  '.': 'q2',
  '/': 'q2',
  ':': 'q2',
  ';': 'q2',
  '<': 'q2',
  '=': 'q2',
  '>': 'q2',
  '?': 'q2',
  '@': 'q2',
  '[': 'q2',
  '\\': 'q2',
  ']': 'q2',
  '^': 'q2',
  '_': 'q2',
  '`': 'q2',
  '{': 'q2',
  '|': 'q2',
  '}': 'q2',
  '~': 'q2',
  ' ': 'q2',
  '\t': 'q2',
  '\n': 'q2',
  '\r': 'q2',
  '\x0b': 'q2',
  '\x0c': 'q2'},
 'q1': {'0': 'q2',
  '1': 'q2',
  '2': 'q2',
  '3': 'q2',
  '4': 'q2',
  '5': 'q2',
  '6': 'q2',
  '7': 'q2',
  '8': 'q2',
  '9': 'q2',
  'a': 'q1',
  'b': 'q1',
  'c': 'q1',
  'd': 'q1',
  'e': 'q1',
  'f': 'q1',
  'g': 'q1',
  'h': 'q1',
  'i': 'q1',
  'j': 'q1',
  'k': 'q1',
  'l': 'q1',
  'm': 'q1',
  'n': 'q1',
  'o': 'q1',
  'p': 'q1',
  'q': 'q1',
  'r': 'q1',
  's': 'q1',
  't': 'q1',
  'u': 'q1',
  'v': 'q1',
  'w': 'q1',
  'x': 'q1',
  'y': 'q1',
  'z': 'q1',
  'A': 'q2',
  'B': 'q2',
  'C': 'q2',
  'D': 'q2',
  'E': 'q2',
  'F': 'q2',
  'G': 'q2',
  'H': 'q2',
  'I': 'q2',
  'J': 'q2',
  'K': 'q2',
  'L': 'q2',
  'M': 'q2',
  'N': 'q2',
  'O': 'q2',
  'P': 'q2',
  'Q': 'q2',
  'R': 'q2',
  'S': 'q2',
  'T': 'q2',
  'U': 'q2',
  'V': 'q2',
  'W': 'q2',
  'X': 'q2',
  'Y': 'q2',
  'Z': 'q2',
  '!': 'q2',
  '"': 'q2',
  '#': 'q2',
  '$': 'q2',
  '%': 'q2',
  '&': 'q2',
  "'": 'q2',
  '(': 'q2',
  ')': 'q2',
  '*': 'q2',
  '+': 'q2',
  ',': 'q2',
  '-': 'q2',
  '.': 'q2',
  '/': 'q2',
  ':': 'q2',
  ';': 'q2',
  '<': 'q2',
  '=': 'q2',
  '>': 'q2',
  '?': 'q2',
  '@': 'q2',
  '[': 'q2',
  '\\': 'q2',
  ']': 'q2',
  '^': 'q2',
  '_': 'q2',
  '`': 'q2',
  '{': 'q2',
  '|': 'q2',
  '}': 'q2',
  '~': 'q2',
  ' ': 'q2',
  '\t': 'q2',
  '\n': 'q2',
  '\r': 'q2',
  '\x0b': 'q2',
  '\x0c': 'q2'},
 'q2': {'0': 'q2',
  '1': 'q2',
  '2': 'q2',
  '3': 'q2',
  '4': 'q2',
  '5': 'q2',
  '6': 'q2',
  '7': 'q2',
  '8': 'q2',
  '9': 'q2',
  'a': 'q2',
  'b': 'q2',
  'c': 'q2',
  'd': 'q2',
  'e': 'q2',
  'f': 'q2',
  'g': 'q2',
  'h': 'q2',
  'i': 'q2',
  'j': 'q2',
  'k': 'q2',
  'l': 'q2',
  'm': 'q2',
  'n': 'q2',
  'o': 'q2',
  'p': 'q2',
  'q': 'q2',
  'r': 'q2',
  's': 'q2',
  't': 'q2',
  'u': 'q2',
  'v': 'q2',
  'w': 'q2',
  'x': 'q2',
  'y': 'q2',
  'z': 'q2',
  'A': 'q2',
  'B': 'q2',
  'C': 'q2',
  'D': 'q2',
  'E': 'q2',
  'F': 'q2',
  'G': 'q2',
  'H': 'q2',
  'I': 'q2',
  'J': 'q2',
  'K': 'q2',
  'L': 'q2',
  'M': 'q2',
  'N': 'q2',
  'O': 'q2',
  'P': 'q2',
  'Q': 'q2',
  'R': 'q2',
  'S': 'q2',
  'T': 'q2',
  'U': 'q2',
  'V': 'q2',
  'W': 'q2',
  'X': 'q2',
  'Y': 'q2',
  'Z': 'q2',
  '!': 'q2',
  '"': 'q2',
  '#': 'q2',
  '$': 'q2',
  '%': 'q2',
  '&': 'q2',
  "'": 'q2',
  '(': 'q2',
  ')': 'q2',
  '*': 'q2',
  '+': 'q2',
  ',': 'q2',
  '-': 'q2',
  '.': 'q2',
  '/': 'q2',
  ':': 'q2',
  ';': 'q2',
  '<': 'q2',
  '=': 'q2',
  '>': 'q2',
  '?': 'q2',
  '@': 'q2',
  '[': 'q2',
  '\\': 'q2',
  ']': 'q2',
  '^': 'q2',
  '_': 'q2',
  '`': 'q2',
  '{': 'q2',
  '|': 'q2',
  '}': 'q2',
  '~': 'q2',
  ' ': 'q2',
  '\t': 'q2',
  '\n': 'q2',
  '\r': 'q2',
  '\x0b': 'q2',
  '\x0c': 'q2'}}

In [29]:
from visual_automata.fa.dfa import VisualDFA

In [30]:


dfa = VisualDFA(

    states=states,

    input_symbols=input_symbols,

    transitions=transitions,

    initial_state=initial_state,

    final_states=final_states

)

In [31]:
dfa.table

,\t,\n,,,\r,,!,"""",#,$,...,u,v,w,x,y,z,{,|,},~
→q0,q2,q2,q2,q2,q2,q2,q2,q2,q2,q2,...,*q1,*q1,*q1,*q1,*q1,*q1,q2,q2,q2,q2
*q1,q2,q2,q2,q2,q2,q2,q2,q2,q2,q2,...,*q1,*q1,*q1,*q1,*q1,*q1,q2,q2,q2,q2
q2,q2,q2,q2,q2,q2,q2,q2,q2,q2,q2,...,q2,q2,q2,q2,q2,q2,q2,q2,q2,q2

In [32]:
dfa.input_check("ab1")

          [Rejected]
Step: Current state: Input symbol: New state:
1                →q0             a        *q1
2                *q1             b        *q1
3                *q1             1         q2

In [33]:
dfa.input_check("abc")

          [Accepted]
Step: Current state: Input symbol: New state:
1                →q0             a        *q1
2                *q1             b        *q1
3                *q1             c        *q1

2. You are given all the nouns from the brown corpus (brown_nouns.txt). You need to
design a finite state transducer (FST) to generate the morph/grammatical features for
every word in the corpus. 

>Your output should look like the following:
>- foxes = fox+N+PL (can be generalized as root+category+number)
>- fox = fox+N+SG [where SG->Singular, PL->Plural, N->Noun]
>- You need to take the following properties:
>- Name Rule Description Example
E insertion e is added after -s, -z, -x,
-ch, -sh before -s is added

watch/watches, fox/foxes

>- Y replacement -y changes to -ie before -s try/tries
>- S addition -s is added at the end bag/bags
You need to ensure that incorrect words are not generated. You return an output “Invalid
Word” in that case. Example: foxs = “Invalid Word”

In [34]:
from pathlib import Path
path = Path('brown_nouns.txt')
data = []
with path.open('r', encoding="utf") as f:
    for i,word in enumerate(f):
        if i<10:
            print(word)
        data.append(word.strip())

investigation

primary

election

evidence

irregularities

place

jury

presentments

charge

election

In [35]:
len(data)
word_dict = set(data)

### Finite State Tranducer which performs morphological analysis.
assume the transitions which do not have letters are all letters except the one with transition.
![dfa image](fst_3.png)

In [36]:
class fst:
    def __init__(self, start_state, input_symbols, output_symbols, state_transition, output_function, final_state):
        self.start_state = start_state
        self.input_symbols = input_symbols
        self.output_symbols = output_symbols
        self.state_transition = state_transition
        self.output_function = output_function
        self.final_state = final_state

    def correct(self, string:str):
        end = string.find("+")
        base_word = string[:end]

        if string.find('+SG')!=-1 or string.find('+invalid')!=-1:
            return string if base_word in word_dict else "invalid word"
        i_1 = base_word.rfind("ies")
        if i_1 != -1:
            candidate = base_word[:i_1] +'y'
            if candidate in word_dict:
                return candidate + string[end:]
            else:
                return base_word + "+N+SG" if base_word in word_dict else "invalid word"
        i_2 = base_word.rfind('es')
        if i_2 != -1:
            candidate = base_word[:i_2]
            if candidate in word_dict:
                return base_word[:i_2] + string[end:]
            else:
                return base_word + "+N+SG" if base_word in word_dict else "invalid word"
        n = len(base_word)
        if n >1:
            candidate = base_word[:n-1]
            if candidate in word_dict:
                return base_word[:n-1] + string[end:]
            else:
                return base_word + "+N+SG" if base_word in word_dict else "invalid word"
        return "invalid word"

        
    def parse(self, string):
        curr_state = self.start_state
        #Special fst specifically for this problem: Consists of one final state: qend which is only reached when the string is completed
        qend = self.final_state
        analysis = []
        i =0
        while curr_state != qend:
            curr_input = "" if i >= len(string) else string[i]
            i+=1
            new_state = self.state_transition[curr_state][curr_input]
            curr_output = self.output_function[curr_state][curr_input]
            curr_state = new_state
            if curr_output != "":
                analysis.append(curr_output)

        analysed = "".join(analysis)
        final = self.correct(analysed)
        return final

In [37]:
import string
inputs = list(string.ascii_letters)
inputs + ['']

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '']

### Transitions and fst defintion

>
>- normal character → qst
>- c                → qc
>- x,z              → q_special
>- s                → q_s
>- EOF              → qend (+N+SG)

In [38]:
start_state = 'qst'
final_state = 'qend'

states = [
    'qst',
    'qc',
    'q_special',
    'qe',
    'qes',
    'q_s_error',
    'q_s',
    'qend'
]

In [39]:
import string

inputs = list(string.ascii_letters)

for word in data:
    for ch in word.strip():
        if ch not in inputs:
            inputs.append(ch)

inputs.append('')

outputs = list(string.ascii_letters) + [
    '', '+N+SG', '+N+PL', '+invalid'
]

# States
start_state = 'qst'
final_state = 'qend'

states = [
    'qst',
    'qc',
    'q_special',
    'qe',
    'qes',
    'q_s_error',
    'q_s',
    'qend'
]


# qst

qst_transitions = {}
qst_output = {}

for ch in inputs:

    if ch not in ['c', 's', 'x', 'z', '']:
        qst_transitions[ch] = 'qst'
        qst_output[ch] = ch

qst_transitions['c'] = 'qc'
qst_output['c'] = 'c'

qst_transitions['s'] = 'q_s'
qst_output['s'] = 's'

for ch in ['x', 'z']:
    qst_transitions[ch] = 'q_special'
    qst_output[ch] = ch

qst_transitions[''] = 'qend'
qst_output[''] = '+N+SG'


# qc

qc_transitions = {}
qc_output = {}

for ch in inputs:

    if ch == 'h':
        qc_transitions[ch] = 'q_special'
        qc_output[ch] = 'h'

    elif ch == '':
        qc_transitions[ch] = 'qend'
        qc_output[ch] = '+N+SG'

    else:
        qc_transitions[ch] = 'qst'
        qc_output[ch] = ch


# q_special

q_special_transitions = {}
q_special_output = {}

for ch in inputs:

    if ch == 'e':
        q_special_transitions[ch] = 'qe'
        q_special_output[ch] = 'e'

    elif ch == 's':
        q_special_transitions[ch] = 'q_s_error'
        q_special_output[ch] = 's'

    elif ch == '':
        q_special_transitions[ch] = 'qend'
        q_special_output[ch] = '+N+SG'

    else:
        q_special_transitions[ch] = 'qst'
        q_special_output[ch] = ch


# q_s

q_s_transitions = {}
q_s_output = {}

for ch in inputs:

    if ch == '':
        q_s_transitions[ch] = 'qend'
        q_s_output[ch] = '+N+PL'

    elif ch == 'e':
        q_s_transitions[ch] = 'qe'
        q_s_output[ch] = 'e'

    elif ch == 'h':
        q_s_transitions[ch] = 'q_special'
        q_s_output[ch] = 'h'

    else:
        q_s_transitions[ch] = 'qst'
        q_s_output[ch] = ch


# qe

qe_transitions = {}
qe_output = {}

for ch in inputs:

    if ch == 's':
        qe_transitions[ch] = 'qes'
        qe_output[ch] = 's'

    elif ch == '':
        qe_transitions[ch] = 'qend'
        qe_output[ch] = '+N+SG'

    else:
        qe_transitions[ch] = 'qst'
        qe_output[ch] = ch


# qes

qes_transitions = {}
qes_output = {}

for ch in inputs:

    if ch == '':
        qes_transitions[ch] = 'qend'
        qes_output[ch] = '+N+PL'

    else:
        qes_transitions[ch] = 'qst'
        qes_output[ch] = ch


# q_s_error

q_s_error_transitions = {}
q_s_error_output = {}

for ch in inputs:

    if ch == '':
        q_s_error_transitions[ch] = 'qend'
        q_s_error_output[ch] = '+invalid'

    else:
        q_s_error_transitions[ch] = 'qst'
        q_s_error_output[ch] = ch


transitions = {
    'qst': qst_transitions,
    'qc': qc_transitions,
    'q_special': q_special_transitions,
    'qe': qe_transitions,
    'qes': qes_transitions,
    'q_s': q_s_transitions,
    'q_s_error': q_s_error_transitions
}

output_function = {
    'qst': qst_output,
    'qc': qc_output,
    'q_special': q_special_output,
    'qe': qe_output,
    'qes': qes_output,
    'q_s': q_s_output,
    'q_s_error': q_s_error_output
}

In [40]:
my_fst = fst(
    start_state=start_state,
    input_symbols=inputs,
    output_symbols=outputs,
    state_transition=transitions,
    output_function=output_function,
    final_state=final_state
)

In [41]:
print(my_fst.parse("buses"))

bus+N+PL

In [42]:
my_fst.parse("irregularities")

'irregularity+N+PL'

In [43]:
#test over first 50 words
for i in range(50):
    print(my_fst.parse(data[i]))

investigation+N+SG
primary+N+SG
election+N+SG
evidence+N+SG
irregularity+N+PL
place+N+SG
jury+N+SG
presentments+N+SG
charge+N+SG
election+N+SG
praise+N+SG
thanks+N+SG
manner+N+SG
election+N+SG
term+N+SG
jury+N+SG
report+N+PL
irregularity+N+PL
primary+N+SG
handful+N+SG
report+N+PL
jury+N+SG
interest+N+SG
election+N+SG
number+N+SG
voter+N+PL
size+N+SG
city+N+SG
jury+N+SG
registration+N+SG
election+N+SG
law+N+PL
legislator+N+PL
law+N+PL
end+N+SG
jury+N+SG
number+N+SG
topics+N+SG
department+N+PL
practices+N+SG
interest+N+SG
government+N+PL
jury+N+SG
offices+N+SG
efficiency+N+SG
cost+N+SG
administration+N+SG
jury+N+SG
personnel+N+SG
result+N+SG

In [44]:
from pathlib import Path

output = Path("output.txt")

with output.open("w", encoding="utf-8") as f:
    for word in data:
        result = my_fst.parse(word.strip())
        f.write(result + "\n")

In [49]:
my_fst.parse('boxes')

'box+N+PL'